@isTest
public with sharing class TestEpisodeController {
    
    

    @isTest
    static void testSaveRecord(){
        //TODO make actual tests here
        System.assert(true);
    }

    @isTest
    static void testUpdateRecord(){
        //TODO make actual tests here
        System.assert(true);
    }

    @isTest
    static void testDeleteRecord() {
        //TODO make actual tests here
        System.assert(true);
    }

    @isTest
    static void testGetEpisodeById(){
        //TODO make actual tests here
        System.assert(true);
    }

    @isTest
    static void testSaveRecordWithPermission(){
        //TODO make actual tests here
        System.assert(true);
    }

    @isTest
    static void testUpdateRecordWithPermission() {
        //TODO make actual tests here
        System.assert(true);
    }
    @isTest
    static void testDeleteRecordWithPermission() {
        //TODO make actual tests here
        System.assert(true);
    }

}
